import type { Digest, SummarizedItem } from "../sources/types.js";

function formatDate(date: Date): string {
  return date.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderItem(item: SummarizedItem, index: number): string {
  const sourceIcon = item.source === "twitter" ? "🐦" : "📧";
  const link = item.url
    ? `<a href="${escapeHtml(item.url)}" style="color: #2563eb; text-decoration: none;">${escapeHtml(item.title)}</a>`
    : escapeHtml(item.title);

  const takeaways =
    item.keyTakeaways.length > 0
      ? `<ul style="margin: 8px 0 0 0; padding-left: 20px; color: #4b5563;">
        ${item.keyTakeaways.map((t) => `<li style="margin: 4px 0;">${escapeHtml(t)}</li>`).join("")}
      </ul>`
      : "";

  return `
    <div style="margin-bottom: 20px; padding: 16px; background: #f9fafb; border-radius: 8px;">
      <div style="display: flex; align-items: flex-start; gap: 8px;">
        <span style="font-size: 14px;">${sourceIcon}</span>
        <div style="flex: 1;">
          <h3 style="margin: 0 0 8px 0; font-size: 16px; font-weight: 600; color: #111827;">
            ${index + 1}. ${link}
          </h3>
          <p style="margin: 0 0 8px 0; color: #374151; font-size: 14px; line-height: 1.5;">
            ${escapeHtml(item.summary)}
          </p>
          ${takeaways}
          <div style="margin-top: 8px; display: flex; gap: 8px; flex-wrap: wrap;">
            ${item.topics
              .map(
                (topic) =>
                  `<span style="display: inline-block; padding: 2px 8px; background: #e5e7eb; color: #374151; font-size: 12px; border-radius: 4px;">${escapeHtml(topic)}</span>`
              )
              .join("")}
          </div>
        </div>
      </div>
    </div>
  `;
}

export function renderDigestHtml(digest: Digest): string {
  const dateStr = formatDate(digest.generatedAt);

  const topStoriesHtml = digest.topStories
    .map((item, i) => renderItem(item, i))
    .join("");

  const sectionsHtml = digest.sections
    .map(
      (section) => `
      <div style="margin-top: 32px;">
        <h2 style="margin: 0 0 16px 0; font-size: 18px; font-weight: 600; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px;">
          ${escapeHtml(section.topic)}
        </h2>
        ${section.items.map((item, i) => renderItem(item, i)).join("")}
      </div>
    `
    )
    .join("");

  const statsHtml = `
    <div style="margin-top: 32px; padding: 16px; background: #f3f4f6; border-radius: 8px; font-size: 12px; color: #6b7280;">
      <strong>Sources:</strong> ${digest.sourceStats.twitterCount} tweets, ${digest.sourceStats.gmailCount} newsletters |
      <strong>Articles extracted:</strong> ${digest.sourceStats.articlesExtracted} |
      <strong>Failed:</strong> ${digest.sourceStats.failedExtractions}
      ${digest.errors.length > 0 ? `<br><strong>Errors:</strong> ${digest.errors.join(", ")}` : ""}
    </div>
  `;

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Daily Digest - ${dateStr}</title>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background: #ffffff; color: #111827;">
  <div style="max-width: 600px; margin: 0 auto; padding: 24px;">

    <!-- Header -->
    <div style="text-align: center; margin-bottom: 32px;">
      <h1 style="margin: 0 0 8px 0; font-size: 28px; font-weight: 700; color: #111827;">
        🤖 AI Daily Digest
      </h1>
      <p style="margin: 0; color: #6b7280; font-size: 14px;">
        ${dateStr}
      </p>
    </div>

    <!-- Executive Summary -->
    <div style="margin-bottom: 32px; padding: 20px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 12px; color: white;">
      <h2 style="margin: 0 0 12px 0; font-size: 16px; font-weight: 600; opacity: 0.9;">
        📋 Executive Summary
      </h2>
      <p style="margin: 0; font-size: 15px; line-height: 1.6;">
        ${escapeHtml(digest.executiveSummary)}
      </p>
    </div>

    <!-- Top Stories -->
    <div style="margin-bottom: 32px;">
      <h2 style="margin: 0 0 16px 0; font-size: 20px; font-weight: 700; color: #111827;">
        🔥 Top Stories
      </h2>
      ${topStoriesHtml}
    </div>

    <!-- Topic Sections -->
    ${sectionsHtml}

    <!-- Footer -->
    ${statsHtml}

    <div style="margin-top: 24px; text-align: center; font-size: 12px; color: #9ca3af;">
      <p style="margin: 0;">
        Generated by AI Daily Digest
      </p>
    </div>

  </div>
</body>
</html>
  `;
}

export function renderDigestSubject(digest: Digest): string {
  const dateStr = digest.generatedAt.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
  });
  const topStory = digest.topStories[0]?.title.slice(0, 50) || "Your daily AI news";
  return `AI Digest ${dateStr}: ${topStory}${topStory.length >= 50 ? "..." : ""}`;
}
